"""HTTP client wrapper with rate limiting and consistent UA.

All outbound HTTP traffic generated by scanners and recon modules MUST go
through :class:`Client`. The client enforces the per-target rate limit
declared in ``scope.yaml`` and stamps every request with a SentinelWeb
User-Agent so target operators can identify the traffic.

When an authenticated :class:`Session` is attached, the client injects
its cookies and headers ONLY for hosts that the active
:class:`ScopePolicy` considers in-scope. This prevents authentication
material from leaking to embedded/third-party hosts that the target
might redirect to or load resources from.
"""

from __future__ import annotations

import asyncio
import time
from collections import defaultdict
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any
from urllib.parse import urlparse

import httpx

from .. import __version__

if TYPE_CHECKING:
    from ..scope.policy import ScopePolicy
    from ..scope.session import Session

DEFAULT_UA = (
    f"SentinelWeb/{__version__} "
    "(+https://github.com/wraithen0/sentinelweb; whitehat-only)"
)


@dataclass
class RateLimiter:
    """Simple per-host token bucket. Async-safe."""

    rate_per_sec: float = 2.0
    _last: dict[str, float] = field(default_factory=lambda: defaultdict(float))
    _lock: asyncio.Lock = field(default_factory=asyncio.Lock)

    async def acquire(self, host: str) -> None:
        if self.rate_per_sec <= 0:
            return
        min_gap = 1.0 / self.rate_per_sec
        async with self._lock:
            now = time.monotonic()
            last = self._last[host]
            wait = max(0.0, last + min_gap - now)
            if wait > 0:
                await asyncio.sleep(wait)
            self._last[host] = time.monotonic()


class Client:
    """Async HTTP client honoring scope rate limits."""

    def __init__(
        self,
        rate_per_sec: float = 2.0,
        timeout: float = 10.0,
        verify_tls: bool = True,
        user_agent: str = DEFAULT_UA,
        max_redirects: int = 5,
        session: Session | None = None,
        policy: ScopePolicy | None = None,
    ) -> None:
        self._limiter = RateLimiter(rate_per_sec=rate_per_sec)
        self._session = session
        self._policy = policy
        self._client = httpx.AsyncClient(
            timeout=timeout,
            verify=verify_tls,
            headers={"User-Agent": user_agent, "Accept": "*/*"},
            follow_redirects=False,
            max_redirects=max_redirects,
        )

    async def request(
        self,
        method: str,
        url: str,
        *,
        follow_redirects: bool = False,
        **kwargs: Any,
    ) -> httpx.Response:
        host = urlparse(url).hostname or ""
        await self._limiter.acquire(host)
        if self._session is not None and self._policy is not None:
            self._inject_session(url, kwargs)
        return await self._client.request(
            method, url, follow_redirects=follow_redirects, **kwargs
        )

    def _inject_session(self, url: str, kwargs: dict[str, Any]) -> None:
        """Merge session cookies/headers into ``kwargs`` for in-scope hosts.

        The :class:`Session` already enforces scope checks in
        ``cookies_for`` / ``headers_for``; this just merges the result
        with any caller-supplied ``cookies`` / ``headers`` without
        clobbering them.

        Cookies are emitted as a single ``Cookie`` header (rather than
        the deprecated per-request ``cookies=`` kwarg) so the choice of
        which cookies to send is fully scoped to the destination host
        without mutating shared client state.
        """
        assert self._session is not None and self._policy is not None
        existing_h: dict[str, str] = dict(kwargs.get("headers") or {})
        existing_keys_lower = {k.lower() for k in existing_h}

        session_cookies = self._session.cookies_for(url, self._policy)
        if session_cookies and "cookie" not in existing_keys_lower:
            cookie_value = "; ".join(f"{c.name}={c.value}" for c in session_cookies)
            existing_h["Cookie"] = cookie_value
            existing_keys_lower.add("cookie")

        session_headers = self._session.headers_for(url, self._policy)
        for k, v in session_headers.items():
            if k.lower() not in existing_keys_lower:
                existing_h[k] = v

        if existing_h:
            kwargs["headers"] = existing_h

    async def get(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("GET", url, **kwargs)

    async def head(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("HEAD", url, **kwargs)

    async def aclose(self) -> None:
        await self._client.aclose()


@asynccontextmanager
async def make_client(**kwargs: Any) -> AsyncIterator[Client]:
    client = Client(**kwargs)
    try:
        yield client
    finally:
        await client.aclose()
