"""HTTP client wrapper with rate limiting and consistent UA.

All outbound HTTP traffic generated by scanners and recon modules MUST go
through :class:`Client`. The client enforces the per-target rate limit
declared in ``scope.yaml`` and stamps every request with a SentinelWeb
User-Agent so target operators can identify the traffic.
"""

from __future__ import annotations

import asyncio
import time
from collections import defaultdict
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlparse

import httpx

from .. import __version__

DEFAULT_UA = (
    f"SentinelWeb/{__version__} "
    "(+https://github.com/wraithen0/sentinelweb; whitehat-only)"
)


@dataclass
class RateLimiter:
    """Simple per-host token bucket. Async-safe."""

    rate_per_sec: float = 2.0
    _last: dict[str, float] = field(default_factory=lambda: defaultdict(float))
    _lock: asyncio.Lock = field(default_factory=asyncio.Lock)

    async def acquire(self, host: str) -> None:
        if self.rate_per_sec <= 0:
            return
        min_gap = 1.0 / self.rate_per_sec
        async with self._lock:
            now = time.monotonic()
            last = self._last[host]
            wait = max(0.0, last + min_gap - now)
            if wait > 0:
                await asyncio.sleep(wait)
            self._last[host] = time.monotonic()


class Client:
    """Async HTTP client honoring scope rate limits."""

    def __init__(
        self,
        rate_per_sec: float = 2.0,
        timeout: float = 10.0,
        verify_tls: bool = True,
        user_agent: str = DEFAULT_UA,
        max_redirects: int = 5,
    ) -> None:
        self._limiter = RateLimiter(rate_per_sec=rate_per_sec)
        self._client = httpx.AsyncClient(
            timeout=timeout,
            verify=verify_tls,
            headers={"User-Agent": user_agent, "Accept": "*/*"},
            follow_redirects=False,
            max_redirects=max_redirects,
        )

    async def request(
        self,
        method: str,
        url: str,
        *,
        follow_redirects: bool = False,
        **kwargs: Any,
    ) -> httpx.Response:
        host = urlparse(url).hostname or ""
        await self._limiter.acquire(host)
        return await self._client.request(
            method, url, follow_redirects=follow_redirects, **kwargs
        )

    async def get(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("GET", url, **kwargs)

    async def head(self, url: str, **kwargs: Any) -> httpx.Response:
        return await self.request("HEAD", url, **kwargs)

    async def aclose(self) -> None:
        await self._client.aclose()


@asynccontextmanager
async def make_client(**kwargs: Any) -> AsyncIterator[Client]:
    client = Client(**kwargs)
    try:
        yield client
    finally:
        await client.aclose()
